[package]
name = "games"
version = "0.1.0"
authors = ["Justus Croskery <justus@olmmcc.tk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.52"
hyper = "0.13.5"
tokio = { version = "0.2.20", features = ["full"]}
session = { git = "https://github.com/Somebody62/session" }
